project_id: sametsplayground
location: europe-west4
tag_template_id: column_description_template
datacatalog_endpoint: datacatalog.googleapis.com # (optional - internal endpoint datacatalog-erste..)
database_connections:
  - database: ORCL19
    user: catalog_reader
    password: "catalog_reader" # Or use password_kms_key for KMS
    #Secret -> password_secret_id: "projects/sametsplayground/locations/europe-west4/keyRings/your-key-ring/cryptoKeys/your-crypto-key"
    host: 34.141.235.166
    port: 1521
    service_name: ORCL19
table_mapping_file: table_mapping.yaml