project_id: your-project-id
location: us-central1
tag_template_id: oracle_column_comments
datacatalog_endpoint: datacatalog.googleapis.com (optional)
database_connections:
  - database: your_database_name
    user: your_oracle_username
    password_kms_key: your-kms-key-name
    host: your_oracle_host
    port: 1521
    service_name: your_oracle_service_name
table_mapping_file: table_mapping.json